cam = view_camera[0];
following = obj_player;
h_border = 60;
v_border = 30;
buff = 32;
view_w_half = camera_get_view_width(cam) * 0.5;
view_h_half = camera_get_view_height(cam) * 0.5;
x_to = xstart;
y_to = ystart;